######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 19 19:29:54 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

LIBS += -lX11 -lXrandr

# Input
SOURCES += main.cpp \
    rotationdaemon.cpp

HEADERS += \
    rotationdaemon.h
